import { LanguageCode, SiteContent } from '../models/content.model';

export const CONTENT: Record<LanguageCode, SiteContent> = {
  sr: {
    lang: 'sr',
    meta: {
      title: 'Business Process & Digital Transformation Advisory',
      description: 'Nezavisno savetovanje za unapređenje poslovnih procesa, digitalizaciju, management analytics i tehnološke odluke.',
    },
    brand: {
      name: 'Advisor Name',
      role: 'Business Process & Digital Transformation Advisor',
    },
    nav: [
      { label: 'Ekspertiza', href: '#expertise' },
      { label: 'Kako radim', href: '#process' },
      { label: 'O meni', href: '#about' },
      { label: 'Kontakt', href: '#contact' },
    ],
    hero: {
      eyebrow: 'Independent advisory practice',
      title: 'Vaša kompanija je porasla. Da li su procesi porasli sa njom?',
      text: 'Pomažem kompanijama da pronađu operativna uska grla, unaprede poslovne procese i donesu bolje odluke o digitalizaciji.',
      expertise: 'Business Process Improvement · Management Analytics · Digitalization Advisory',
      primaryCta: 'Razgovarajmo o problemu',
      secondaryCta: 'Kako izgleda angažman',
      panelKicker: 'Senior · Independent · Selective',
      panelText: 'Ne počinjem od softvera. Počinjem od poslovnog problema.',
    },
    sectionLabels: {
      problems: 'Prepoznavanje problema',
      engagements: 'Modeli angažovanja',
      advice: 'Nezavisni tehnološki savet',
      process: 'Proces',
      selectedProblems: 'Tipični problemi',
      about: 'O meni',
      contact: 'Kontakt',
    },
    problems: {
      title: 'Da li vam ovo zvuči poznato?',
      intro: 'Pravi problem se obično vidi kroz svakodnevne simptome: kasne informacije, ručni rad i odluke koje čekaju podatke.',
      items: [
        { icon: 'table', title: 'Excel je postao poslovni sistem', text: 'Ključni procesi zavise od tabela koje samo nekoliko ljudi razume.' },
        { icon: 'schedule', title: 'Informacije kasne', text: 'Menadžment dobija odgovore tek nakon mnogo ručnog rada.' },
        { icon: 'hub', title: 'ERP postoji, ali proces živi mimo njega', text: 'Podaci se vode paralelno kroz mailove, tabele i privatne evidencije.' },
        { icon: 'content_copy', title: 'Isti podatak se unosi više puta', text: 'Ljudi troše vreme na administraciju umesto na posao.' },
        { icon: 'person_alert', title: 'Proces zavisi od pojedinca', text: 'Ako ključna osoba nije tu, niko nije siguran šta je sledeći korak.' },
        { icon: 'settings_suggest', title: 'Digitalizacija počinje od softvera', text: 'Pre nego što je jasno definisan poslovni problem.' },
      ],
    },
    engagements: {
      title: 'Tri načina angažovanja',
      intro: 'Bez tradicionalnog cenovnika i bez univerzalnih paketa. Angažman se definiše prema odluci, procesu ili promeni koju treba razjasniti.',
      items: [
        {
          title: 'Executive Second Opinion',
          label: 'Fokusiran angažman',
          text: 'Za situacije kada već imate problem, predlog ili ponudu i treba vam nezavisno mišljenje pre nego što donesete odluku.',
          meta: ['Management-level discussion', 'Independent perspective', 'Key risks and next steps'],
        },
        {
          title: 'Process Diagnostic',
          label: 'Core offer',
          text: 'Za procese za koje znate da ne funkcionišu dobro, ali još nije jasno gde je pravi uzrok.',
          meta: ['Process mapping', 'Root-cause analysis', 'Prioritized recommendations'],
        },
        {
          title: 'Transformation Blueprint',
          label: 'Širi plan promene',
          text: 'Za kompanije koje žele ozbiljnije da promene način rada i potreban im je jasan plan pre implementacije.',
          meta: ['AS-IS / TO-BE process', 'Operating model and KPIs', 'Implementation roadmap'],
        },
      ],
    },
    advice: {
      title: 'Ne počinjem od softvera.',
      text: 'Novi ERP, aplikacija ili automatizacija mogu da budu deo rešenja. Ali ako proces nije dobro definisan, tehnologija samo ubrzava postojeći problem.',
      principles: [
        { icon: 'business_center', title: 'Business first', text: 'Prvo razumemo problem i poslovni cilj.' },
        { icon: 'verified', title: 'Independent advice', text: 'Preporuka nije vezana za određeni ERP, platformu ili dobavljača.' },
        { icon: 'query_stats', title: 'Technology-aware', text: 'Rešenje mora biti i poslovno opravdano i tehnički realno.' },
      ],
    },
    process: {
      title: 'Kako izgleda angažman',
      intro: 'Rad je fokusiran, dogovoren po fazama i usmeren na konkretan poslovni rezultat.',
      steps: [
        { number: '01', title: 'Razgovor', text: 'Definišemo problem i očekivani rezultat.' },
        { number: '02', title: 'Razumevanje procesa', text: 'Razgovori sa ljudima, dokumentacija, sistemi i podaci.' },
        { number: '03', title: 'Dijagnostika', text: 'Identifikacija uzroka, uskih grla, rizika i nepotrebne kompleksnosti.' },
        { number: '04', title: 'Predlog', text: 'Bolji proces, KPI, digitalizacija ili preporuka za donošenje odluke.' },
        { number: '05', title: 'Roadmap', text: 'Šta prvo, ko je odgovoran i kako meriti rezultat.' },
      ],
    },
    selectedProblems: {
      title: 'Tipični problemi koje analiziram',
      items: [
        'Kako ubrzati proces od izvršenja usluge do fakturisanja.',
        'Kako menadžmentu omogućiti pravovremen pregled profitabilnosti.',
        'Kako smanjiti ručne unose između različitih sistema.',
        'Kako definisati zahteve pre zamene ERP ili poslovnog sistema.',
        'Kako digitalizovati servisni ili terenski proces.',
        'Kako proceniti da li predložena automatizacija rešava pravi problem.',
      ],
    },
    availability: {
      label: 'Independent advisory practice',
      title: 'Ograničen broj konsultantskih angažmana',
      paragraphs: [
        'Van svog primarnog profesionalnog angažmana prihvatam ograničen broj nezavisnih savetodavnih projekata, prvenstveno kroz preporuke i direktne kontakte.',
        'Projekti su fokusirani na jasno definisane poslovne probleme, a dostupnost se dogovara u skladu sa obimom i prioritetom angažmana.',
        'Zbog ograničenog kapaciteta prihvatam samo projekte kod kojih verujem da mogu da napravim konkretnu poslovnu razliku.',
      ],
      badges: ['Limited engagements', 'Primarily by referral', 'Project-based advisory'],
    },
    about: {
      title: 'Kratko o meni',
      paragraphs: [
        'Softverski i poslovni konsultant sa dugogodišnjim iskustvom u unapređenju poslovnih procesa i informacionih sistema.',
        'Povremeno, van svog primarnog profesionalnog angažmana, prihvatam ograničen broj nezavisnih savetodavnih projekata - prvenstveno kroz preporuke.',
      ],
      tags: 'Business Processes · Operations · Digitalization · Technology Advisory',
    },
    contact: {
      title: 'Imate proces za koji mislite da može da radi bolje?',
      text: 'Opišite problem u nekoliko rečenica. Ako procenim da postoji dobar profesionalni fit, prvi razgovor možemo iskoristiti da definišemo šta bi imalo smisla dalje analizirati.',
      form: {
        name: 'Ime i prezime',
        company: 'Kompanija',
        email: 'Email',
        phone: 'Telefon (opciono)',
        message: 'Koji problem pokušavate da rešite?',
        submit: 'Pošalji upit',
        success: 'Hvala. Upit je pripremljen za slanje.',
        error: 'Nešto nije prošlo kako treba. Pokušajte ponovo ili pošaljite email direktno.',
        required: 'Popunite obavezna polja.',
        privacy: 'Zbog ograničenog broja angažmana, svaki upit prvo pregledam kako bih procenio da li postoji dobar profesionalni fit.',
      },
    },
    footer: {
      text: 'Advisor Name Advisory. Nezavisno savetovanje za poslovne procese i digitalnu transformaciju.',
      links: [
        { label: 'Email', href: 'mailto:hello@example.com' },
        { label: 'LinkedIn', href: 'https://www.linkedin.com/' },
      ],
    },
  },
  en: {
    lang: 'en',
    meta: {
      title: 'Business Process & Digital Transformation Advisory',
      description: 'Independent advisory for business process improvement, digitalization, management analytics, and technology decisions.',
    },
    brand: {
      name: 'Advisor Name',
      role: 'Business Process & Digital Transformation Advisor',
    },
    nav: [
      { label: 'Expertise', href: '#expertise' },
      { label: 'How I Work', href: '#process' },
      { label: 'About', href: '#about' },
      { label: 'Contact', href: '#contact' },
    ],
    hero: {
      eyebrow: 'Independent advisory practice',
      title: 'Your company has grown. Have your processes grown with it?',
      text: 'I help companies identify operational bottlenecks, improve business processes, and make better decisions about digitalization.',
      expertise: 'Business Process Improvement · Management Analytics · Digitalization Advisory',
      primaryCta: 'Discuss the problem',
      secondaryCta: 'How engagement works',
      panelKicker: 'Senior · Independent · Selective',
      panelText: 'I do not start with software. I start with the business problem.',
    },
    sectionLabels: {
      problems: 'Problem recognition',
      engagements: 'Engagement models',
      advice: 'Independent technology advice',
      process: 'Process',
      selectedProblems: 'Selected problems',
      about: 'About',
      contact: 'Contact',
    },
    problems: {
      title: 'Does this sound familiar?',
      intro: 'Operational issues often appear as familiar symptoms: delayed information, manual work, and decisions waiting for reliable data.',
      items: [
        { icon: 'table', title: 'Excel has become the business system', text: 'Critical processes depend on spreadsheets understood by only a few people.' },
        { icon: 'schedule', title: 'Information arrives late', text: 'Management gets answers only after extensive manual consolidation.' },
        { icon: 'hub', title: 'ERP exists, but the process lives outside it', text: 'Data is still tracked through email, files, and private records.' },
        { icon: 'content_copy', title: 'The same data is entered repeatedly', text: 'People spend time on administration instead of the actual work.' },
        { icon: 'person_alert', title: 'The process depends on one person', text: 'When a key person is unavailable, the next step becomes unclear.' },
        { icon: 'settings_suggest', title: 'Digitalization starts with software', text: 'Before the business problem has been clearly defined.' },
      ],
    },
    engagements: {
      title: 'Three ways to engage',
      intro: 'No traditional price list and no universal packages. Each engagement is shaped around a decision, process, or change that needs clarity.',
      items: [
        {
          title: 'Executive Second Opinion',
          label: 'Focused engagement',
          text: 'For situations where you already have a problem, proposal, vendor offer, or project concept and need an independent view before deciding.',
          meta: ['Management-level discussion', 'Independent perspective', 'Key risks and next steps'],
        },
        {
          title: 'Process Diagnostic',
          label: 'Core offer',
          text: 'For processes you know are not working well, but where the real cause is not yet clear.',
          meta: ['Process mapping', 'Root-cause analysis', 'Prioritized recommendations'],
        },
        {
          title: 'Transformation Blueprint',
          label: 'Broader change plan',
          text: 'For companies that want to make a serious operational change and need a clear plan before implementation.',
          meta: ['AS-IS / TO-BE process', 'Operating model and KPIs', 'Implementation roadmap'],
        },
      ],
    },
    advice: {
      title: 'I do not start with software.',
      text: 'A new ERP, application, or automation may be part of the answer. But if the process is not clearly defined, technology only accelerates the existing problem.',
      principles: [
        { icon: 'business_center', title: 'Business first', text: 'We first understand the problem and the business objective.' },
        { icon: 'verified', title: 'Independent advice', text: 'Recommendations are not tied to a specific ERP, platform, or vendor.' },
        { icon: 'query_stats', title: 'Technology-aware', text: 'The solution must be commercially justified and technically realistic.' },
      ],
    },
    process: {
      title: 'How engagement works',
      intro: 'The work is focused, milestone-oriented, and directed toward a concrete business outcome.',
      steps: [
        { number: '01', title: 'Conversation', text: 'We define the problem and the expected result.' },
        { number: '02', title: 'Process understanding', text: 'Interviews, documentation, systems, and available data.' },
        { number: '03', title: 'Diagnostic', text: 'Identifying causes, bottlenecks, risks, and unnecessary complexity.' },
        { number: '04', title: 'Recommendation', text: 'A better process, KPI, digitalization path, or decision recommendation.' },
        { number: '05', title: 'Roadmap', text: 'What comes first, who owns it, and how success is measured.' },
      ],
    },
    selectedProblems: {
      title: 'Typical problems I analyze',
      items: [
        'How to accelerate the process from service delivery to invoicing.',
        'How to give management timely visibility into profitability.',
        'How to reduce manual entries between different systems.',
        'How to define requirements before replacing an ERP or business system.',
        'How to digitalize a service or field process.',
        'How to assess whether a proposed automation solves the right problem.',
      ],
    },
    availability: {
      label: 'Independent advisory practice',
      title: 'A limited number of advisory engagements',
      paragraphs: [
        'Outside my primary professional role, I accept a limited number of independent advisory projects, primarily through referrals and direct professional introductions.',
        'Projects are focused on clearly defined business problems, with availability agreed according to engagement scope and priority.',
        'Because capacity is limited, I only accept projects where I believe I can create a concrete business difference.',
      ],
      badges: ['Limited engagements', 'Primarily by referral', 'Project-based advisory'],
    },
    about: {
      title: 'Briefly about me',
      paragraphs: [
        'A software and business consultant with long-standing experience improving business processes and information systems.',
        'Occasionally, outside my primary professional role, I accept a limited number of independent advisory projects - primarily through referrals.',
      ],
      tags: 'Business Processes · Operations · Digitalization · Technology Advisory',
    },
    contact: {
      title: 'Do you have a process that should work better?',
      text: 'Describe the issue in a few sentences. If there is a strong professional fit, the first conversation can clarify what would make sense to analyze next.',
      form: {
        name: 'Full name',
        company: 'Company',
        email: 'Email',
        phone: 'Phone (optional)',
        message: 'What problem are you trying to solve?',
        submit: 'Send inquiry',
        success: 'Thank you. The inquiry is ready to be sent.',
        error: 'Something went wrong. Please try again or send an email directly.',
        required: 'Please complete the required fields.',
        privacy: 'Because engagement capacity is limited, every inquiry is reviewed first to assess whether there is a good professional fit.',
      },
    },
    footer: {
      text: 'Advisor Name Advisory. Independent advisory for business processes and digital transformation.',
      links: [
        { label: 'Email', href: 'mailto:hello@example.com' },
        { label: 'LinkedIn', href: 'https://www.linkedin.com/' },
      ],
    },
  },
  ru: {
    lang: 'ru',
    meta: {
      title: 'Консалтинг по бизнес-процессам и цифровой трансформации',
      description: 'Независимый консалтинг по улучшению бизнес-процессов, цифровизации, управленческой аналитике и технологическим решениям.',
    },
    brand: {
      name: 'Advisor Name',
      role: 'Business Process & Digital Transformation Advisor',
    },
    nav: [
      { label: 'Экспертиза', href: '#expertise' },
      { label: 'Подход', href: '#process' },
      { label: 'О себе', href: '#about' },
      { label: 'Контакт', href: '#contact' },
    ],
    hero: {
      eyebrow: 'Independent advisory practice',
      title: 'Ваша компания выросла. Выросли ли вместе с ней процессы?',
      text: 'Помогаю компаниям находить операционные узкие места, улучшать бизнес-процессы и принимать более точные решения о цифровизации.',
      expertise: 'Business Process Improvement · Management Analytics · Digitalization Advisory',
      primaryCta: 'Обсудить проблему',
      secondaryCta: 'Как проходит работа',
      panelKicker: 'Senior · Independent · Selective',
      panelText: 'Я не начинаю с программного обеспечения. Я начинаю с бизнес-проблемы.',
    },
    sectionLabels: {
      problems: 'Распознавание проблемы',
      engagements: 'Форматы работы',
      advice: 'Независимый технологический консалтинг',
      process: 'Процесс',
      selectedProblems: 'Типичные задачи',
      about: 'О себе',
      contact: 'Контакт',
    },
    problems: {
      title: 'Похоже на вашу ситуацию?',
      intro: 'Проблемы процессов обычно проявляются через знакомые симптомы: запаздывающую информацию, ручной труд и решения без своевременных данных.',
      items: [
        { icon: 'table', title: 'Excel стал рабочей системой', text: 'Ключевые процессы зависят от таблиц, которые понимают только несколько человек.' },
        { icon: 'schedule', title: 'Информация приходит поздно', text: 'Руководство получает ответы только после длительной ручной подготовки.' },
        { icon: 'hub', title: 'ERP есть, но процесс живет отдельно', text: 'Данные параллельно ведутся в почте, файлах и личных реестрах.' },
        { icon: 'content_copy', title: 'Один и тот же показатель вводится несколько раз', text: 'Люди тратят время на администрирование вместо основной работы.' },
        { icon: 'person_alert', title: 'Процесс зависит от одного человека', text: 'Если ключевой сотрудник недоступен, следующий шаг становится неочевидным.' },
        { icon: 'settings_suggest', title: 'Цифровизация начинается с софта', text: 'До того, как четко определена бизнес-проблема.' },
      ],
    },
    engagements: {
      title: 'Три формата работы',
      intro: 'Без стандартного прайс-листа и универсальных пакетов. Формат определяется решением, процессом или изменением, которое нужно прояснить.',
      items: [
        {
          title: 'Executive Second Opinion',
          label: 'Фокусированная оценка',
          text: 'Для ситуаций, когда уже есть проблема, предложение, оффер поставщика или идея проекта, и перед решением нужна независимая экспертная оценка.',
          meta: ['Разговор на уровне руководства', 'Независимая перспектива', 'Риски и следующие шаги'],
        },
        {
          title: 'Process Diagnostic',
          label: 'Основной формат',
          text: 'Для процессов, которые явно работают не так, как нужно, но настоящая причина еще не определена.',
          meta: ['Карта процесса', 'Анализ первопричин', 'Приоритизированные рекомендации'],
        },
        {
          title: 'Transformation Blueprint',
          label: 'План трансформации',
          text: 'Для компаний, которые хотят серьезно изменить способ работы и нуждаются в ясном плане до начала внедрения.',
          meta: ['AS-IS / TO-BE процесс', 'Операционная модель и KPI', 'Дорожная карта внедрения'],
        },
      ],
    },
    advice: {
      title: 'Я не начинаю с программного обеспечения.',
      text: 'Новая ERP, приложение или автоматизация могут быть частью решения. Но если процесс не определен ясно, технология только ускоряет уже существующую проблему.',
      principles: [
        { icon: 'business_center', title: 'Сначала бизнес', text: 'Сначала разбираемся в проблеме и бизнес-цели.' },
        { icon: 'verified', title: 'Независимая рекомендация', text: 'Рекомендация не привязана к конкретной ERP, платформе или поставщику.' },
        { icon: 'query_stats', title: 'Технологическая реалистичность', text: 'Решение должно быть оправдано для бизнеса и технически реализуемо.' },
      ],
    },
    process: {
      title: 'Как проходит работа',
      intro: 'Работа сфокусирована, идет по согласованным этапам и направлена на конкретный бизнес-результат.',
      steps: [
        { number: '01', title: 'Разговор', text: 'Определяем проблему и ожидаемый результат.' },
        { number: '02', title: 'Понимание процесса', text: 'Интервью, документация, системы и доступные данные.' },
        { number: '03', title: 'Диагностика', text: 'Выявление причин, узких мест, рисков и лишней сложности.' },
        { number: '04', title: 'Рекомендация', text: 'Улучшенный процесс, KPI, направление цифровизации или рекомендация для решения.' },
        { number: '05', title: 'Дорожная карта', text: 'Что делать сначала, кто отвечает и как измерять результат.' },
      ],
    },
    selectedProblems: {
      title: 'Типичные задачи для анализа',
      items: [
        'Как ускорить путь от оказания услуги до выставления счета.',
        'Как дать руководству своевременную видимость прибыльности.',
        'Как сократить ручной ввод между разными системами.',
        'Как определить требования до замены ERP или бизнес-системы.',
        'Как цифровизировать сервисный или выездной процесс.',
        'Как понять, решает ли предложенная автоматизация настоящую проблему.',
      ],
    },
    availability: {
      label: 'Independent advisory practice',
      title: 'Ограниченное количество консультационных проектов',
      paragraphs: [
        'Вне моей основной профессиональной роли я принимаю ограниченное количество независимых консультационных проектов, преимущественно через рекомендации и прямые профессиональные контакты.',
        'Проекты сфокусированы на четко определенных бизнес-проблемах, а доступность согласуется с учетом объема и приоритета работы.',
        'Из-за ограниченной емкости я принимаю только те проекты, где считаю возможным создать конкретную бизнес-ценность.',
      ],
      badges: ['Ограниченные проекты', 'Преимущественно по рекомендации', 'Проектный консалтинг'],
    },
    about: {
      title: 'Коротко обо мне',
      paragraphs: [
        'Консультант по программным решениям и бизнесу с многолетним опытом улучшения бизнес-процессов и информационных систем.',
        'Периодически, вне моей основной профессиональной роли, я принимаю ограниченное количество независимых консультационных проектов - преимущественно через рекомендации.',
      ],
      tags: 'Business Processes · Operations · Digitalization · Technology Advisory',
    },
    contact: {
      title: 'Есть процесс, который должен работать лучше?',
      text: 'Опишите проблему в нескольких предложениях. Если профессиональный fit будет хорошим, первая встреча поможет определить, что имеет смысл анализировать дальше.',
      form: {
        name: 'Имя и фамилия',
        company: 'Компания',
        email: 'Email',
        phone: 'Телефон (необязательно)',
        message: 'Какую проблему вы хотите решить?',
        submit: 'Отправить запрос',
        success: 'Спасибо. Запрос подготовлен к отправке.',
        error: 'Что-то пошло не так. Попробуйте еще раз или отправьте email напрямую.',
        required: 'Заполните обязательные поля.',
        privacy: 'Из-за ограниченного количества проектов каждый запрос сначала рассматривается, чтобы оценить профессиональный fit.',
      },
    },
    footer: {
      text: 'Advisor Name Advisory. Независимый консалтинг по бизнес-процессам и цифровой трансформации.',
      links: [
        { label: 'Email', href: 'mailto:hello@example.com' },
        { label: 'LinkedIn', href: 'https://www.linkedin.com/' },
      ],
    },
  },
};
